
import NavbarComponent from '@/components/NavbarComponent'
import './globals.css'
import NavigationContext from '@/context/NavigationContext'


export const metadata = {
  title: 'Testing toolkit',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavigationContext>
      <body className='w-full min-h-screen bg-[#072a54] flex flex-col items-center justify-center'>
            <div className='lg:hidden w-full min-h-screen bg-white flex  item-center pt-[100px] justify-center font-extrabold text-xl'>BE A GOOD BOY AND TRY AGAIN ON A PC INSTEAD!!!!!</div>
          <div className='hidden lg:flex flex-col max-w-3xl w-[80%] mx-auto h-[85vh] border-2 rounded-2xl border-black overflow-hidden'>
                  <NavbarComponent /> 
                  {children}
        </div>
        </body>
        </NavigationContext>
    </html>
  )
}
